name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        play-version: [ 2.7.3, 2.7.9, 2.8.0, 2.8.7, 2.8.8 ]
        java-version: [ 8, 11 ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}

    - name: Cache SBT
      uses: actions/cache@v2
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt', '**/plugins.sbt') }}-play${{ matrix.play-version }}

    - name: Run tests
      run: sbt "testPlayVersion ${{ matrix.play-version }}"
